services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: library-music
      PG_DATA: /var/lib/postgresql/data/
    ports:
      - 5431:5432
    volumes:
      - db:/var/lib/postgresql/data/
volumes:
  db: