basePath: /
definitions:
  domain.Music:
    properties:
      group:
        type: string
      id:
        type: integer
      link:
        type: string
      releaseDate:
        type: string
      song:
        type: string
      text:
        type: string
    type: object
  domain.MusicToAdd:
    properties:
      group:
        type: string
      link:
        type: string
      releaseDate:
        type: string
      song:
        type: string
      text:
        type: string
    type: object
  domain.MusicToUpdate:
    properties:
      group:
        type: string
      link:
        type: string
      releaseDate:
        type: string
      song:
        type: string
      text:
        type: string
    type: object
host: localhost:8090
info:
  contact: {}
  description: API Server for Library music application
  title: Library music API
  version: "1.0"
paths:
  /api/add:
    post:
      consumes:
      - application/json
      description: Create a new music
      operationId: create-music
      parameters:
      - description: Music info to add
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.MusicToAdd'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: AddMusic
      tags:
      - music
  /api/delete:
    delete:
      consumes:
      - application/json
      description: delete music
      operationId: delete-music
      parameters:
      - description: Id song
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: DeleteMusic
      tags:
      - music
  /api/getAll:
    get:
      consumes:
      - application/json
      description: get all music
      operationId: get-all-music
      parameters:
      - description: Song name
        in: query
        name: song
        type: string
      - description: Music group
        in: query
        name: group
        type: string
      - description: Link song
        in: query
        name: link
        type: string
      - description: Text song
        in: query
        name: text
        type: string
      - description: Page number
        in: query
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/domain.Music'
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: GetAllMusic
      tags:
      - music
  /api/getText:
    get:
      consumes:
      - application/json
      description: get text music
      operationId: get-text-music
      parameters:
      - description: Song name
        in: query
        name: song
        required: true
        type: string
      - description: Music group
        in: query
        name: group
        required: true
        type: string
      - description: Page number
        in: query
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: GetTextMusic
      tags:
      - music
  /api/info:
    get:
      consumes:
      - application/json
      description: get music
      operationId: get-music
      parameters:
      - description: Song name
        in: query
        name: song
        required: true
        type: string
      - description: Music group
        in: query
        name: group
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Music'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: GetMusic
      tags:
      - music
  /api/update:
    put:
      consumes:
      - application/json
      description: update music
      operationId: update-music
      parameters:
      - description: Id song
        in: query
        name: id
        required: true
        type: integer
      - description: Music info to update
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.MusicToUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: UpdateMusic
      tags:
      - music
swagger: "2.0"
